### ISSUE TITLE
Add carets on package.json

### ISSUE THREAD

**Issue by kbariotis** [DSchau/gatsby-blog-starter-kit#4]
Are [these tildes](https://github.com/DSchau/gatsby-blog-starter-kit/blob/master/package.json#L7) necessary? They are forcing you to use an older version of Gatsby.

Thanks

**Comment by DSchau** [comment]
Generally a personal preference, but open to a PR changing the behavior!

In other words, some prefer the "safety" of pinning versions (e.g. 1.1.0 gets you 1.1.9 but not 1.2.0), while others want the bleeding edge.

**Comment by DSchau** [comment]
I implemented greenkeeper (and bumped the versions!) in e25fd8d6eda44705a9c12651186f72118c76b790, so this should be less of an issue.

Going forward, greenkeeper will monitor the deps, alerting when any new deps release with a PR, so I'll try and keep this updated whenever new deps are released.

Hope this will address this issue; thanks!
