### ISSUE TITLE
breaks w/ latest gatsby-source-filesystem

### ISSUE THREAD

**Issue by brandonmp** [DSchau/gatsby-blog-starter-kit#5]
Followed tutorial in gatsby docs, but kept getting an error. cloned this repo and updated deps one at a time to trace it, and sure enough, updating `gatsby-source-filesystem` to latest breaks it

```
error Plugin default-site-plugin returned an error


  Error:

success createPages — 0.018 s
success createPagesStatefully — 0.016 s
GraphQL Error Unknown field `allMarkdownRemark` on type `RootQueryType`

  file: /home/bmp/code/gatsby-admitbrain/src/pages/index.js

   1 |
   2 |   query IndexQuery {
>  3 |     allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
     |     ^
   4 |       edges {
   5 |         node {
   6 |           excerpt(pruneLength: 250)
   7 |           id
   8 |           frontmatter {
   9 |             title
  10 |             date(formatString: "MMMM DD, YYYY")
  11 |             path
  12 |           }
  13 |
```

**Comment by DSchau** [comment]
Is latest `2.0.0-alpha` or `1.4.6`?

Regardless, this starter kit should be resistant to this as it currently pins the version to `~1.0.1`, so this isn't necessarily an issue on my end.

That said, once `2.0.0` moves out of alpha, I'll likely be updating this to the latest versions of plugins.

**Comment by DSchau** [comment]
Hi Brandon!

Gonna close this, but please re-open if I was off base

**Comment by brandonmp** [comment]
Ah, sorry, missed your reply

by latest I mean `1.4.6`

understood re: pinning the version. just wanted to pass a note since this repo is ref'd in a semi-official tutorial

**Comment by DSchau** [comment]
Right, but that's only if you manually upgrade things, correct? I just ran `yarn` when you opened this and it still worked for me!

But like I said, want to fix it, so I'll try and take a look soon!

**Comment by DSchau** [comment]
@brandonmp PRs welcome too! If you happen to figure out what's going on, happy to get something merged in!

**Comment by DSchau** [comment]
@brandonmp I think I fixed this :) Updated all my deps, and didn't run into anything.

Feel free to check out the latest from master, but seems to work on my end. I also added greenkeeper, which will keep the dependencies up to date, and open up a PR (automatically!) whenever upstream deps are updated. Pretty cool!

Let me know, if you have any time!
