### ISSUE TITLE
Cannot read property 'allMarkdownRemark' of undefined

### ISSUE THREAD

**Issue by danocnl** [DSchau/gatsby-blog-starter-kit#9]
I just cloned the repo and I am getting the error in the title: 

```
Uncaught TypeError: Cannot read property 'allMarkdownRemark' of undefined at new Index (index.js:9)
```

```
The above error occurred in the <Index> component:
```

```
Uncaught TypeError: Cannot read property 'allMarkdownRemark' of undefined at new Index (index.js:9)
```

I installed with yarn.

**Comment by DSchau** [comment]
Any errors in `yarn`, or did that install successfully?

**Comment by danocnl** [comment]
You are right, it is a dependency (sharp) causing problems. [I have raised an issue there](https://github.com/lovell/sharp/issues/969). Thanks!

**Comment by DSchau** [comment]
@theorise I was running into the same thing locally (after re-cloning) so I should've mentioned I was running into the same! I'll subscribe to that issue; thanks!
